export interface Basicrecord {
  "g_id": string,
  "chr": string,
  "start": number,
  "end": number,
  "strand":string,
  "score":number,
  "group":string
  "gene_id":string,
  "gene_name":string,
  "gene_type":string,
  "size":string,
  "phastCons": number,
  "phyloP": number,
  "eqtl_cancer_number": number,
  "eqtl_gtex_number": number,
  "eqtl_gwas_number": number,
  "distance":number,
  "sample_number":number,
  "rl1": number,
  "rl2": number,
  "rl3": number,
  "ll1": number,
  "ll2": number,
  "ll3": number,
  "seq": string
}
